### ISSUE TITLE
Crash in tableview

### ISSUE THREAD

**Issue by fabiosoft** [jasarien/CoreTextHyperlinkView#10]
when used in a tableview (inside a custom cell) it makes app crashing... why?
no errors or warnings...just crash :(

**Comment by jasarien** [comment]
Could you perhaps post the stack trace for the crash or the exception reason, possibly?

**Comment by fabiosoft** [comment]
no stacktrace in console...but here it is the SIGKILL
![Schermata 2013-03-11 alle 21 26 13](https://f.cloud.github.com/assets/812037/245733/1ef9e658-8a8a-11e2-931c-e5e0eace67ca.png)

**Comment by jasarien** [comment]
Could you give some more details on how to reproduce the crash? Does it happen immediately when the table view loads or after some time? Do you need to scroll the table view?

**Comment by fabiosoft** [comment]
I subcalssed an uitableviewcell customizing it via xib and custom code...when i tap on a link or mention app crashes. the delegate call is so simple... here it is: 
![Schermata 2013-03-11 alle 21 33 58](https://f.cloud.github.com/assets/812037/245760/2729b5dc-8a8b-11e2-93cb-425c6a54e6d3.png)

**Comment by jasarien** [comment]
I added a table view example to the example xcode project and wasn't able to reproduce the crash. Pull from master and have a look at the example to see if you're doing the same thing?

Without more information, I can't tell what your issue is...

**Comment by fabiosoft** [comment]
i am going to try this new example and discover differences....thanks

**Comment by yberdnikov** [comment]
please, see my commit 1e2db90 - I just have same crash because of using JSCoreTextView in xib file for custom cell.
