### ISSUE TITLE
Wrong tap detection on link

### ISSUE THREAD

**Issue by yberdnikov** [jasarien/CoreTextHyperlinkView#12]
The issue reproduces when tap on link which is last element in line but not fill line till the end. For better understanding, please see image attached bellow.

![issue](https://f.cloud.github.com/assets/1654654/291118/14c41610-92fd-11e2-88b2-4f8285a95084.png)

I googled some solution and looks like issue is in JSCoreTextView.m touchesBegan method, because CTLineGetStringIndexForPosition returns value no less than the first string index and no greater than the last string index plus 1.
Possible solution could be call CTLineGetOffsetForStringIndex to verify if touch location is in link range.

**Comment by JagnaSz** [comment]
Does anybody know how to fix this problem?

**Comment by jasarien** [comment]
There is a possible solution suggested in the original issue description using CTLineGetOffsetForStringIndex, but I haven't had a chance to try it or figure it out. If you manage to find a solution, I'd be happy to accept a pull request.

**Comment by yberdnikov** [comment]
@JagnaSz, I fixed it by adding verification in `touchesBegan` method from JSCoreTextView.m (last few lines):

```
    CGFloat xOffset = CTLineGetOffsetForStringIndex(line, index, NULL);

    if (fabs(location.x - xOffset) < 10)
    {
        for (AHMarkedHyperlink *link in _links)
        {
            if (((index >= [link range].location) && (index <= ([link range].length + [link range].location))))
            {
                _touchedLink = link;
                [self setNeedsDisplay];
            }
        }
    }

    if (!_touchedLink)
        [super touchesBegan:touches withEvent:event];
```

**Comment by jasarien** [comment]
if you want to create a pull request for that I'll merge it in.

**Comment by yberdnikov** [comment]
@jasarien it was more then year ago, and it worked for me, but I'm not 100% sure about that fix now. But if you want, I can create pull request

**Comment by jasarien** [comment]
I tried your code and it seems to do the job, so I'll commit and push it and give you a byline in the commit message.

**Comment by yberdnikov** [comment]
Thank you
