### ISSUE TITLE
Wrong Display on IOS5.1 with Chinese

### ISSUE THREAD

**Issue by RafaelZ** [jasarien/CoreTextHyperlinkView#14]
![vp1y8709 te7 770w w5](https://f.cloud.github.com/assets/3303118/1397165/954be894-3c80-11e3-9247-6170e773e694.jpg)
![z hq1ibrrsb hu mut vfx](https://f.cloud.github.com/assets/3303118/1397166/9654de8a-3c80-11e3-8af8-c0ee64448851.jpg)
It's correct on IOS6+ ,but on IOS5.1,the chinese text looks bolder.How to solve this problem?

**Comment by jasarien** [comment]
I'm afraid I don't know. I've not dealt with Chinese text in Core Text before. I will say, however, that iOS 7 has been out for a couple of weeks now, why are you still supporting 5.1?

I will even go as far to say that with some of the new NSAttributedString stuff in iOS 7 and the support for Link Data Dectectors and being able to handle them yourself with UITextView means that JSCoreTextHyperlinkView is now redundant.

**Comment by RafaelZ** [comment]
Thanks for your response.And I have to try to find some other method.
