### ISSUE TITLE
Problem with AutoHyperlinks

### ISSUE THREAD

**Issue by LeonS** [jasarien/CoreTextHyperlinkView#4]
Hi,

I'm trying to integrate your nice piece of code into my project but after adding it, I can't compile. Two things happen: Xcode crashes or I'm getting 2560 failures. I think the root of that failure is the AutoHyperlinks library. The curious thing is that within a new project everything works fine, just in my current project with some other frameworks it will crash xcode. 
Does anybody has this problem and knows how to solve it?

thanks

**Comment by jasarien** [comment]
Could you please post an exerpt of the compilation errors you are getting? Autohyperlinks is a relatively small library and shoudnt have any dependencies that aren't already in a standard Xcode project.

**Comment by jasarien** [comment]
Closing this issue, as I don't believe it to be related to the CoreTextHyperlinkView code or AutoHyperlinks, and I have received no further information on the issue.
