### ISSUE TITLE
JSTwitterCoreTextView crashes in detectLinks

### ISSUE THREAD

**Issue by joshuafeldman** [jasarien/CoreTextHyperlinkView#5]
If NSArray *matches is nil the application crashes. I love this class, I was using it inside of a reusable UITableViewCell. I added a catch to see if that value is nil and if it was I just returned.

**Comment by joshuafeldman** [comment]
Here is some more information in case I am incorrect.

0   CoreFoundation           0x017b8be9 __exceptionPreprocess + 185
1   libobjc.A.dylib              0x0190d5c2 objc_exception_throw + 47
2   CoreFoundation            0x01771628 +[NSException raise:format:arguments:] + 136
3   CoreFoundation             0x0177159a +[NSException raise:format:] + 58
4   Foundation                    0x0031a139 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 224
5   Foundation                    0x00317097 -[NSRegularExpression(NSMatching) matchesInString:options:range:] + 150
6   --------------------                0x000c9dc5 -[JSTwitterCoreTextView detectLinks] + 610

**Comment by jasarien** [comment]
It's not matches that is nil, it's the text being sent to the regular expression search. If the text is nil the regular expression API throws an invalid argument exception.

I have patched the crasher, but this view isn't intended to be used with a nil text property. The result would be undefined behaviour.
